version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=data
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3307:3306

  app:
    depends_on:
       - docker-mysql
    build: ../Timesheet
    ports:
       - 9090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/data?autoReconnect=true&useSSL=false
    