version: '3.8'

services:
  docker-mysql:
    image: 'mysql:5.7'
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=boot
    ports:
      - "3307:3306"

  app:
    image: hatembayoudh/timesheet
    depends_on:
      - docker-mysql
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "9090:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://docker-mysql:3306/boot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
